/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppConfirmDialog: typeof import('./src/components/AppConfirmDialog.vue')['default']
    AppNavbar: typeof import('./src/components/AppNavbar.vue')['default']
    AppNoticeDialog: typeof import('./src/components/AppNoticeDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
